### ISSUE TITLE
Debain 7下Python3报错了，求解决办法。

### ISSUE THREAD

**Issue by lvguanming** [LiuLang/kwplayer#71]
现在的是这个kwplayer_3.4.9-2_all.deb 。
目前的py版本是2.7
-------------------console----------------------
lvgm@debian:~$ kwplayer 
Traceback (most recent call last):
  File "/usr/bin/kwplayer", line 57, in <module>
    main()
  File "/usr/bin/kwplayer", line 54, in main
    load_app()
  File "/usr/bin/kwplayer", line 35, in load_app
    from kuwo.App import App
  File "/usr/lib/python3/dist-packages/kuwo/App.py", line 29, in <module>
    from kuwo.Player import Player
  File "/usr/lib/python3/dist-packages/kuwo/Player.py", line 19, in <module>
    from kuwo.PlayerBin import PlayerBin
  File "/usr/lib/python3/dist-packages/kuwo/PlayerBin.py", line 14, in <module>
    from gi.repository import GstVideo
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 76, in load_module
    dynamic_module._load()
  File "/usr/lib/python3/dist-packages/gi/module.py", line 222, in _load
    version)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 90, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gst' version '0.10', but '1.0' is already loaded
lvgm@debian:~$ python --version
Python 2.7.3

**Comment by LiuLang** [comment]
是gstreamer的问题, 和python没关系. kwplayer用的一直都是python3.
我一会儿测试一下.

**Comment by LiuLang** [comment]
你是怎么安装的kwplayer? 现在的3.4.9-2.deb包里有个问题, 在debian7中直接安装会失败. 现在已经修复了.
请安装3.4.9-3.deb.
我是在debian7+lxde中测试的, 没有问题.

**Comment by lvguanming** [comment]
刚才重新安装了kwplayer_3.4.9-3_all.deb， 现在可以了！！
貌似不支持酷我用户登录功能（API没开放吧？）。
非常好，可以在线听歌了!
感谢伟大的开源者。。。。 :+1:

**Comment by LiuLang** [comment]
不支持用户登录的
