### ISSUE TITLE
kuwo module problem

### ISSUE THREAD

**Issue by mudongliang** [LiuLang/kwplayer#86]
```
$ kwplayer 
sys:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
Traceback (most recent call last):
  File "/usr/bin/kwplayer", line 57, in <module>
    main()
  File "/usr/bin/kwplayer", line 54, in main
    load_app()
  File "/usr/bin/kwplayer", line 35, in load_app
    from kuwo.App import App
ImportError: No module named 'kuwo'
```
What's wrong ? And how do I fix it?

**Comment by LiuLang** [comment]
请问你是怎么安装的? 是下载的deb包么? 操作系统是哪一个? 什么版本的?

**Comment by mudongliang** [comment]
不是下载的deb包，我笔记本是Archlinux，我使用yaourt来安装的，
```
aur/kwplayer 3.5.2-1 [installed] (5)
    An elegant music player which can get songs from kuwo.cn
aur/kwplayer-git r519.d623733-1 (0)
    An elegant music player which can get songs from kuwo.cn
```
我觉得我可能是少了什么python库。

另外，我的Debian台式机使用kwplayer没有任何问题，工作正常。
感谢你的辛苦工作！

**Comment by wangjiezhe** [comment]
Arch 最近由 python3.4 升级到了 python3.5，不在官方仓库里的 python 程序都需要重新编译安装。

**Comment by mudongliang** [comment]
是这个问题，我以前见过一次，我的retext因为python，python-markup等软件的升级导致无法使用，
yaourt -S kwplayer 选择reinstall就行了吧！

**Comment by mudongliang** [comment]
我已经试过了，确实是这个问题，谢谢 @wangjiezhe
